[project]
name = 'defi-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.magic-beans]
path = 'contracts/magic-beans.clar'
clarity_version = 1

[contracts.magic-ms]
path = 'contracts/magic-ms.clar'
clarity_version = 1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
